export const SONGS = [
  {
    title: "Smoke on the Water", artist: "Deep Purple", year: 1972,
    query: "Smoke on the Water Deep Purple",
    hint: "The most famous guitar riff ever written",
    wave: "sawtooth",
    notes: [
      { n: "G3", d: "8n", t: 0 }, { n: "Bb3", d: "8n", t: 0.3 }, { n: "C4", d: "4n", t: 0.6 },
      { n: "G3", d: "8n", t: 1.2 }, { n: "Bb3", d: "8n", t: 1.5 }, { n: "Db4", d: "8n", t: 1.8 },
      { n: "C4", d: "4n", t: 2.1 }, { n: "G3", d: "8n", t: 2.8 }, { n: "Bb3", d: "8n", t: 3.1 },
      { n: "C4", d: "4n", t: 3.4 }, { n: "Bb3", d: "8n", t: 3.9 }, { n: "G3", d: "2n", t: 4.2 },
    ],
  },
  {
    title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987,
    query: "Sweet Child O Mine Guns N Roses",
    hint: "Slash's iconic guitar intro",
    wave: "square",
    notes: [
      { n: "D4", d: "16n", t: 0 }, { n: "D5", d: "16n", t: 0.15 }, { n: "A4", d: "16n", t: 0.3 },
      { n: "G4", d: "16n", t: 0.45 }, { n: "G5", d: "16n", t: 0.6 }, { n: "A4", d: "16n", t: 0.75 },
      { n: "F#5", d: "16n", t: 0.9 }, { n: "A4", d: "16n", t: 1.05 },
      { n: "D4", d: "16n", t: 1.2 }, { n: "D5", d: "16n", t: 1.35 }, { n: "A4", d: "16n", t: 1.5 },
      { n: "G4", d: "16n", t: 1.65 }, { n: "G5", d: "16n", t: 1.8 }, { n: "A4", d: "16n", t: 1.95 },
      { n: "F#5", d: "16n", t: 2.1 }, { n: "A4", d: "16n", t: 2.25 },
    ],
  },
  {
    title: "Back in Black", artist: "AC/DC", year: 1980,
    query: "Back In Black ACDC",
    hint: "One of the best-selling albums ever",
    wave: "sawtooth",
    notes: [
      { n: "E4", d: "8n", t: 0 }, { n: "D4", d: "8n", t: 0.25 }, { n: "A3", d: "4n", t: 0.6 },
      { n: "E4", d: "8n", t: 1.3 }, { n: "D4", d: "8n", t: 1.55 }, { n: "B3", d: "8n", t: 1.8 },
      { n: "A3", d: "4n", t: 2.1 },
      { n: "E4", d: "8n", t: 2.9 }, { n: "D4", d: "8n", t: 3.15 }, { n: "A3", d: "4n", t: 3.5 },
    ],
  },
  {
    title: "Enter Sandman", artist: "Metallica", year: 1991,
    query: "Enter Sandman Metallica",
    hint: "Exit light, enter night",
    wave: "sawtooth",
    notes: [
      { n: "E3", d: "8n", t: 0 }, { n: "E3", d: "16n", t: 0.4 },
      { n: "G3", d: "8n", t: 0.6 }, { n: "E3", d: "16n", t: 0.9 },
      { n: "Bb3", d: "8n", t: 1.1 }, { n: "A3", d: "8n", t: 1.4 },
      { n: "E3", d: "8n", t: 1.7 }, { n: "E3", d: "16n", t: 2.1 },
      { n: "G3", d: "8n", t: 2.3 }, { n: "E3", d: "16n", t: 2.6 },
      { n: "Bb3", d: "8n", t: 2.8 }, { n: "A3", d: "4n", t: 3.1 },
    ],
  },
  {
    title: "Billie Jean", artist: "Michael Jackson", year: 1982,
    query: "Billie Jean Michael Jackson",
    hint: "The kid is not my son",
    wave: "triangle",
    notes: [
      { n: "F#3", d: "8n", t: 0 }, { n: "F#3", d: "8n", t: 0.25 },
      { n: "F#3", d: "8n", t: 0.5 }, { n: "F#3", d: "16n", t: 0.75 },
      { n: "A3", d: "8n", t: 0.9 }, { n: "F#3", d: "8n", t: 1.15 },
      { n: "E3", d: "8n", t: 1.4 }, { n: "F#3", d: "4n", t: 1.65 },
    ],
  },
  {
    title: "Crazy Train", artist: "Ozzy Osbourne", year: 1980,
    query: "Crazy Train Ozzy Osbourne",
    hint: "All aboard! Ha ha ha ha!",
    wave: "square",
    notes: [
      { n: "F#4", d: "16n", t: 0 }, { n: "F#5", d: "16n", t: 0.12 },
      { n: "F#4", d: "16n", t: 0.24 }, { n: "F#5", d: "16n", t: 0.36 },
      { n: "F#4", d: "16n", t: 0.48 }, { n: "F#5", d: "16n", t: 0.6 },
      { n: "E4", d: "16n", t: 0.72 }, { n: "E5", d: "16n", t: 0.84 },
      { n: "D4", d: "16n", t: 0.96 }, { n: "D5", d: "16n", t: 1.08 },
      { n: "C#4", d: "16n", t: 1.2 }, { n: "D4", d: "16n", t: 1.32 },
      { n: "C#4", d: "16n", t: 1.44 }, { n: "B3", d: "16n", t: 1.56 },
      { n: "A3", d: "4n", t: 1.68 },
    ],
  },
  {
    title: "Another One Bites the Dust", artist: "Queen", year: 1980,
    query: "Another One Bites The Dust Queen",
    hint: "That iconic bass line",
    wave: "sawtooth",
    notes: [
      { n: "E2", d: "8n", t: 0 }, { n: "E2", d: "8n", t: 0.2 }, { n: "E2", d: "8n", t: 0.4 },
      { n: "G2", d: "8n", t: 0.7 }, { n: "A2", d: "16n", t: 1.0 }, { n: "A2", d: "8n", t: 1.2 },
      { n: "B2", d: "4n", t: 1.5 },
    ],
  },
  {
    title: "Seven Nation Army", artist: "The White Stripes", year: 2003,
    query: "Seven Nation Army White Stripes",
    hint: "Da da da da da-da daaa (the stadium chant)",
    wave: "sawtooth",
    notes: [
      { n: "E3", d: "4n", t: 0 }, { n: "E3", d: "8n", t: 0.5 },
      { n: "G3", d: "4n", t: 0.8 }, { n: "E3", d: "8n", t: 1.3 },
      { n: "D3", d: "4n", t: 1.6 }, { n: "C3", d: "2n", t: 2.1 },
      { n: "B2", d: "2n", t: 3.0 },
    ],
  },
  {
    title: "Iron Man", artist: "Black Sabbath", year: 1970,
    query: "Iron Man Black Sabbath",
    hint: "Has he lost his mind? Can he see or is he blind?",
    wave: "sawtooth",
    notes: [
      { n: "B3", d: "4n", t: 0 }, { n: "D4", d: "4n", t: 0.5 },
      { n: "D4", d: "8n", t: 1.0 }, { n: "E4", d: "4n", t: 1.3 },
      { n: "E4", d: "8n", t: 1.8 }, { n: "G4", d: "8n", t: 2.1 },
      { n: "F#4", d: "8n", t: 2.4 }, { n: "G4", d: "8n", t: 2.7 },
      { n: "F#4", d: "8n", t: 3.0 }, { n: "E4", d: "8n", t: 3.3 },
      { n: "D4", d: "4n", t: 3.6 },
    ],
  },
  {
    title: "Eye of the Tiger", artist: "Survivor", year: 1982,
    query: "Eye Of The Tiger Survivor",
    hint: "Rocky III's anthem",
    wave: "square",
    notes: [
      { n: "C4", d: "16n", t: 0 }, { n: "C4", d: "16n", t: 0.15 }, { n: "C4", d: "16n", t: 0.3 },
      { n: "C4", d: "8n", t: 0.55 }, { n: "Bb3", d: "16n", t: 0.85 }, { n: "C4", d: "4n", t: 1.05 },
      { n: "C4", d: "16n", t: 1.7 }, { n: "C4", d: "16n", t: 1.85 }, { n: "C4", d: "16n", t: 2.0 },
      { n: "C4", d: "8n", t: 2.25 }, { n: "Bb3", d: "16n", t: 2.55 }, { n: "Ab3", d: "4n", t: 2.75 },
    ],
  },
  {
    title: "Take on Me", artist: "a-ha", year: 1985,
    query: "Take On Me a-ha",
    hint: "That synth riff and the pencil sketch music video",
    wave: "square",
    notes: [
      { n: "F#4", d: "16n", t: 0 }, { n: "F#4", d: "16n", t: 0.13 },
      { n: "D4", d: "16n", t: 0.26 }, { n: "B3", d: "16n", t: 0.39 },
      { n: "B3", d: "16n", t: 0.65 }, { n: "E4", d: "16n", t: 0.78 },
      { n: "E4", d: "16n", t: 1.04 }, { n: "E4", d: "16n", t: 1.17 },
      { n: "G#4", d: "16n", t: 1.3 }, { n: "G#4", d: "16n", t: 1.43 },
      { n: "A4", d: "16n", t: 1.56 }, { n: "B4", d: "16n", t: 1.69 },
      { n: "A4", d: "16n", t: 1.82 }, { n: "A4", d: "16n", t: 1.95 },
      { n: "A4", d: "16n", t: 2.08 }, { n: "E4", d: "16n", t: 2.21 },
      { n: "D4", d: "16n", t: 2.34 }, { n: "F#4", d: "4n", t: 2.47 },
    ],
  },
  {
    title: "Don't Stop Believin'", artist: "Journey", year: 1981,
    query: "Don't Stop Believin Journey",
    hint: "Just a small town girl...",
    wave: "triangle",
    notes: [
      { n: "E4", d: "8n", t: 0 }, { n: "B4", d: "8n", t: 0.25 }, { n: "C#5", d: "8n", t: 0.5 },
      { n: "E5", d: "8n", t: 0.75 }, { n: "C#5", d: "8n", t: 1.0 }, { n: "B4", d: "8n", t: 1.25 },
      { n: "A4", d: "8n", t: 1.5 }, { n: "B4", d: "8n", t: 1.75 },
    ],
  },
  {
    title: "Bohemian Rhapsody", artist: "Queen", year: 1975,
    query: "Bohemian Rhapsody Queen",
    hint: "Is this the real life? Is this just fantasy?",
    wave: "triangle",
    notes: [
      { n: "Bb4", d: "4n", t: 0 }, { n: "A4", d: "8n", t: 0.4 },
      { n: "Bb4", d: "4n", t: 0.7 }, { n: "G4", d: "8n", t: 1.1 },
      { n: "Eb4", d: "4n", t: 1.5 }, { n: "Bb4", d: "8n", t: 2.0 },
      { n: "A4", d: "8n", t: 2.3 }, { n: "Bb4", d: "4n", t: 2.6 },
      { n: "G4", d: "8n", t: 3.0 }, { n: "Eb4", d: "2n", t: 3.3 },
    ],
  },
  {
    title: "Thunderstruck", artist: "AC/DC", year: 1990,
    query: "Thunderstruck ACDC",
    hint: "You've been...",
    wave: "square",
    notes: [
      { n: "B4", d: "16n", t: 0 }, { n: "E4", d: "16n", t: 0.1 },
      { n: "B4", d: "16n", t: 0.2 }, { n: "A4", d: "16n", t: 0.3 },
      { n: "B4", d: "16n", t: 0.4 }, { n: "G4", d: "16n", t: 0.5 },
      { n: "B4", d: "16n", t: 0.6 }, { n: "A4", d: "16n", t: 0.7 },
      { n: "B4", d: "16n", t: 0.8 }, { n: "E4", d: "16n", t: 0.9 },
      { n: "B4", d: "16n", t: 1.0 }, { n: "A4", d: "16n", t: 1.1 },
      { n: "B4", d: "16n", t: 1.2 }, { n: "G4", d: "16n", t: 1.3 },
      { n: "B4", d: "16n", t: 1.4 }, { n: "A4", d: "16n", t: 1.5 },
    ],
  },
  {
    title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971,
    query: "Stairway To Heaven Led Zeppelin",
    hint: "There's a lady who's sure all that glitters is gold",
    wave: "triangle",
    notes: [
      { n: "A3", d: "8n", t: 0 }, { n: "C4", d: "8n", t: 0.3 },
      { n: "E4", d: "8n", t: 0.6 }, { n: "A4", d: "8n", t: 0.9 },
      { n: "B4", d: "8n", t: 1.2 }, { n: "E4", d: "8n", t: 1.5 },
      { n: "C4", d: "8n", t: 1.8 }, { n: "G#3", d: "8n", t: 2.1 },
      { n: "C4", d: "8n", t: 2.4 }, { n: "E4", d: "8n", t: 2.7 },
      { n: "G#4", d: "8n", t: 3.0 }, { n: "B4", d: "4n", t: 3.3 },
    ],
  },
  {
    title: "Hotel California", artist: "Eagles", year: 1977,
    query: "Hotel California Eagles",
    hint: "You can check out any time you like...",
    wave: "triangle",
    notes: [
      { n: "B3", d: "8n", t: 0 }, { n: "D4", d: "8n", t: 0.3 },
      { n: "F#4", d: "8n", t: 0.6 }, { n: "B4", d: "8n", t: 0.9 },
      { n: "F#4", d: "8n", t: 1.2 }, { n: "A4", d: "8n", t: 1.5 },
      { n: "E4", d: "8n", t: 1.8 }, { n: "G4", d: "8n", t: 2.1 },
      { n: "D4", d: "8n", t: 2.4 }, { n: "F#4", d: "8n", t: 2.7 },
    ],
  },
  {
    title: "Paranoid", artist: "Black Sabbath", year: 1970,
    query: "Paranoid Black Sabbath",
    hint: "Finished with my woman cause she couldn't help me...",
    wave: "sawtooth",
    notes: [
      { n: "E4", d: "8n", t: 0 }, { n: "E4", d: "8n", t: 0.15 },
      { n: "D4", d: "8n", t: 0.3 }, { n: "D4", d: "8n", t: 0.45 },
      { n: "E4", d: "8n", t: 0.6 }, { n: "G4", d: "4n", t: 0.85 },
      { n: "E4", d: "8n", t: 1.3 }, { n: "E4", d: "8n", t: 1.45 },
      { n: "D4", d: "8n", t: 1.6 }, { n: "D4", d: "8n", t: 1.75 },
      { n: "E4", d: "8n", t: 1.9 }, { n: "G4", d: "4n", t: 2.15 },
    ],
  },
  {
    title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986,
    query: "Livin On A Prayer Bon Jovi",
    hint: "Tommy and Gina hold on to what they've got",
    wave: "square",
    notes: [
      { n: "E4", d: "8n", t: 0 }, { n: "E4", d: "8n", t: 0.25 },
      { n: "F#4", d: "8n", t: 0.5 }, { n: "G4", d: "8n", t: 0.75 },
      { n: "G4", d: "8n", t: 1.0 }, { n: "A4", d: "8n", t: 1.25 },
      { n: "G4", d: "4n", t: 1.5 }, { n: "F#4", d: "8n", t: 2.0 },
      { n: "E4", d: "4n", t: 2.25 },
    ],
  },
  {
    title: "Purple Rain", artist: "Prince", year: 1984,
    query: "Purple Rain Prince",
    hint: "I only wanted to see you laughing in the...",
    wave: "triangle",
    notes: [
      { n: "Bb4", d: "4n", t: 0 }, { n: "Ab4", d: "8n", t: 0.5 },
      { n: "F4", d: "4n", t: 0.8 }, { n: "Eb4", d: "8n", t: 1.4 },
      { n: "F4", d: "4n", t: 1.7 }, { n: "Ab4", d: "8n", t: 2.3 },
      { n: "Bb4", d: "2n", t: 2.6 },
    ],
  },
  {
    title: "Sunshine of Your Love", artist: "Cream", year: 1967,
    query: "Sunshine Of Your Love Cream",
    hint: "Eric Clapton's blues-rock masterpiece riff",
    wave: "sawtooth",
    notes: [
      { n: "D3", d: "8n", t: 0 }, { n: "D3", d: "16n", t: 0.3 }, { n: "F3", d: "8n", t: 0.5 },
      { n: "G3", d: "16n", t: 0.8 }, { n: "Ab3", d: "8n", t: 1.0 }, { n: "G3", d: "8n", t: 1.3 },
      { n: "F3", d: "8n", t: 1.6 }, { n: "D3", d: "8n", t: 1.9 }, { n: "F3", d: "8n", t: 2.2 },
      { n: "D3", d: "4n", t: 2.5 },
    ],
  },
];

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
